name: Build Pack

on:
  push:
  pull_request:

concurrency:
  group: "build-${{ github.event.sha }}"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.10.1'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the build script
        run: ./build.py

      - name: Upload the main artifact
        uses: actions/upload-artifact@v2.3.1
        with:
          name: gurkpack
          path: build/gurkpack

      - name: Upload intermediate data
        uses: actions/upload-artifact@v2.3.1
        with:
          name: intermediate
          path: build/intermediate
